'depth': 10
'min_density': 0.1
'n_threads': -1
'downsample': False
'voxel_size': 0.5
'max_nn': 20
'pc_range':  [-50, -50, -5, 50, 50, 3]
'occ_size':  [200, 200, 16]
'self_range': [3.0, 3.0, 3.0]
'cam_list': ['CAM_FRONT', 'CAM_FRONT_RIGHT', 'CAM_BACK_RIGHT', 'CAM_BACK', 'CAM_BACK_LEFT', 'CAM_FRONT_LEFT']
'class_num': 17
'batch_size': 8
'learning_rate': 0.001
'epoch_num': 10